kind: Pod
apiVersion: v1
metadata:
  name: k8sbook-pod
  labels:
    zone: prod
    version: v1
spec:
  containers:
  - name: k8sbook-ctr
    image: nigelpoulton/k8sbook:latest
    ports:
    - containerPort: 8080 