apiVersion: v1
kind: Service
metadata:
  name: htmlcss-svc 
  labels:
    app: htmlcss

spec:
 
  type: NodePort
  ports: 
  - port: 80 #internal cluster port
    nodePort: 30000 #external cluster port 
    protocol: TCP
  selector:
    app: htmlcss   